language: python
python:
  - "2.7"
  - "3.3"
install: 
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
script: 
  - python test.py
after_success:
  - coveralls
